import type { CapacitorConfig } from '@capacitor/cli';

// Phase 8 scaffold. Native android/ and ios/ projects are generated by
// `npx cap add android` / `npx cap add ios`, which requires Android
// Studio / Xcode toolchains not available in this environment — this
// config is the starting point for that phase, not yet executed.
const config: CapacitorConfig = {
  appId: 'in.payrollos.ess',
  appName: 'Payroll OS',
  webDir: 'dist',
  server: {
    androidScheme: 'https',
  },
};

export default config;
